name: wandb
namespace: wandb

global:
  subdomain: "sa-assessment"
  domainName: "wandb.ml"

  # GCS bucket 
  bucket:
    name: "wandb-expert-dassie"
    provider: "gcs"

  # MySQL connection settings
  mysql:
    database: "wandb_local"
    host: "10.124.0.2"
    name: "wandb-sacred-panda"
    port: 3306
    user: "sqlbro"
    secretName: "wandb-credentials"

# w&b license 
license:
  secretName: "wandb-credentials"

ingress:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: "abc-wandb-cert-creative-puma"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "abc-wandb-operator-address"