apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: weightsandbiases
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  values:
    global:
      host: "https://{{ .Values.global.subdomain }}.{{ .Values.global.domainName }}"
      bucket:
        name: "{{ .Values.global.bucket.name }}"
        provider: "{{ .Values.global.bucket.provider }}"
      mysql:
        database: "{{ .Values.global.mysql.database }}"
        host: "{{ .Values.global.mysql.host }}"
        name: "{{ .Values.global.mysql.name }}"
        port: {{ .Values.global.mysql.port }}
        user: "{{ .Values.global.mysql.user }}"
        password:
          secretKeyRef:
            name: "{{ .Values.global.mysql.secretName }}"
            key: mysql-password
    license:
      secretKeyRef:
        name: "{{ .Values.license.secretName }}"
        key: license
    ingress:
      annotations:
{{ toYaml .Values.ingress.annotations | indent 8 }}